---
- name: VMware Reporte Virtual Machines
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    vms_procesar: []
    vmware_hostname: '{{ lookup("env", "VMWARE_HOST") }}'
    vmware_username: '{{ lookup("env", "VMWARE_USER") }}'
    vmware_password: '{{ lookup("env", "VMWARE_PASSWORD") }}'

  tasks:
    - name: "TAREA 1: Obtener inventario de Virtual Machines"
      community.vmware.vmware_vm_info:
        hostname: "{{ vmware_hostname }}"
        username: "{{ vmware_username }}"
        password: "{{ vmware_password }}"
        validate_certs: false
        vm_type: vm
      register: vmware_vm_info

    - name: "TAREA 2: Limpiar y filtrar (Solo Nombre y MoID)"
      set_fact:
        vms_procesar: "{{ vms_procesar + [ {'name': item.guest_name, 'moid': item.moid} ] }}"
      loop: "{{ vmware_vm_info.virtual_machines }}"
      loop_control:
        label: "Agregando Virtual Machine: {{ item.guest_name }}"

    - name: "TAREA 3: Consultar Recursos Detallados (Usando lista limpia)"
      vmware.vmware.vm_resource_info:
        hostname: "{{ vmware_hostname }}"
        username: "{{ vmware_username }}"
        password: "{{ vmware_password }}"
        validate_certs: false
        moid: "{{ item.moid }}"
      loop: "{{ vms_procesar }}"
      register: vmware_vm_resource_info
      loop_control:
        label: "Consultando recursos de {{ item.name }}"

    - name: "TAREA 4: Mostrar Resumen Final"
      ansible.builtin.debug:
        msg:
          - "Nombre: {{ item.item.name }}"
          - "CPUs: {{ item.instance.config.hardware.num_cpu | default('N/A') }}"
          - "Memoria: {{ item.instance.config.hardware.memory_mb | default('N/A') }} MB"
      loop: "{{ vmware_vm_resource_info.results }}"
      loop_control:
        label: "{{ item.item.name }}"
