---
- name: RB - Webhook Hello World
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Run JT - Hello World
      condition: event.payload is defined
      actions:
        - debug:
