---
- name: RB - Webhook Hello World
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Run JT - Hello World
      condition:
        all:
          - event.payload is defined
          - event.payload.run == True
      actions:
        - debug:
        - run_job_template:
          name: "JT - Hello World"
          organization: "Default"
          job_args:
            extra_vars:
              source: "eda-webhook"
              incoming_payload: "{{ event.payload }}"
