---
- name: PB - Iniciar instancia de bus
  hosts: all

  vars:
    bus_name: "{{ bus_name | mandatory }}"

  tasks:
    - name: Iniciar bus
      ansible.builtin.debug:
        msg: "Se inicio el bus {{ bus_name }}"
